// ========================================
// Churches of India — Site Data (Orchestrator)
// Defines sectionMeta, extraSections, getSectionData()
// ========================================

// --- Section Metadata ---
window.sectionMeta = {
    basilica: {
        title: 'Basilicas of India',
        description: 'The 28 designated Minor Basilicas of India — churches of exceptional architectural, historical, and spiritual significance granted special papal recognition.',
        link: 'basilicas.html',
        count: 28
    },
    heritage: {
        title: 'Heritage Churches',
        description: 'UNESCO World Heritage Sites and ASI-protected churches representing centuries of Christian architectural heritage across India.',
        link: 'heritage.html',
        count: 15
    },
    goa: {
        title: 'Churches of Goa',
        description: 'The historic churches and cathedrals of Goa — jewels of Portuguese colonial architecture and living centres of Goan Catholic faith.',
        link: 'goa.html',
        count: 18
    },
    kerala: {
        title: 'Churches of Kerala',
        description: 'Ancient churches of Kerala tracing back to the apostolic mission of St. Thomas in 52 AD, spanning Syrian Orthodox, Latin Catholic, and CSI traditions.',
        link: 'kerala.html',
        count: 20
    },
    tamilnadu: {
        title: 'Churches of Tamil Nadu',
        description: 'From the Santhome Basilica where St. Thomas was martyred to Gothic cathedrals and mission churches across the Tamil countryside.',
        link: 'tamilnadu.html',
        count: 15
    },
    northeast: {
        title: 'Churches of Northeast India',
        description: 'The vibrant churches of Meghalaya, Nagaland, Mizoram, and Manipur — testament to the remarkable growth of Christianity in India\'s northeast.',
        link: 'northeast.html',
        count: 12
    },
    catholic: {
        title: 'Catholic Churches',
        description: 'Prominent Roman Catholic churches across India, from grand cathedrals to parish churches, representing the largest Christian denomination in the country.',
        link: 'catholic.html',
        count: 15
    },
    orthodox: {
        title: 'Orthodox Churches',
        description: 'Churches of the Malankara Orthodox Syrian Church, Jacobite Syrian Church, and other Eastern Orthodox traditions rooted in India since antiquity.',
        link: 'orthodox.html',
        count: 12
    },
    csi: {
        title: 'CSI Churches',
        description: 'Historic churches of the Church of South India — formed in 1947 by the union of Anglican, Methodist, Congregational, Presbyterian, and Reformed traditions.',
        link: 'csi.html',
        count: 12
    },
    protestant: {
        title: 'Protestant Churches',
        description: 'Baptist, Lutheran, Methodist, and other Protestant churches established by European and American missionaries from the 18th century onward.',
        link: 'protestant.html',
        count: 12
    },
    pilgrimage: {
        title: 'Pilgrimage Churches',
        description: 'The most important Christian pilgrimage sites in India — miraculous shrines, martyrdom sites, and places of deep devotion visited by millions.',
        link: 'pilgrimage.html',
        count: 12
    },
    featured: {
        title: 'Featured Churches',
        description: 'A curated selection of India\'s most iconic and architecturally stunning churches spanning every region and tradition.',
        link: 'featured.html',
        count: 10
    }
};

// --- Extra Sections Data ---
window.extraSections = {

    // ===== BASILICAS OF INDIA (28 Minor Basilicas) =====
    basilica: [
        { id: 1, name: 'Basilica of Bom Jesus', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1605', architect: 'Julião Simão', style: 'Baroque', patron: 'Infant Jesus', significance: 'Houses the mortal remains of St. Francis Xavier in a silver casket. UNESCO World Heritage Site. One of the oldest churches in India.', summary: 'UNESCO World Heritage church housing the sacred relics of St. Francis Xavier, a masterpiece of Baroque architecture built in 1605.', image: 'images/basilica/bom-jesus.jpg', lat: 15.5009, lng: 73.9116, timings: '9:00 AM – 6:30 PM (Mon–Sat), 10:30 AM – 6:30 PM (Sun)', festivals: ['Feast of St. Francis Xavier (Dec 3)', 'Exposition of Relics (every 10 years)'] },
        { id: 2, name: 'Se Cathedral', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1640', architect: 'Júlio Simão', style: 'Portuguese-Manueline', patron: 'St. Catherine of Alexandria', significance: 'Largest church in Asia at the time of construction. Seat of the Archbishop of Goa. Famous Golden Bell is the largest in Asia.', summary: 'The magnificent Sé Cathedral, once the largest church in Asia, famed for its Golden Bell and stunning Portuguese-Manueline architecture.', image: 'images/basilica/se-cathedral.jpg', lat: 15.5039, lng: 73.9119, timings: '7:30 AM – 6:00 PM', festivals: ['Feast of St. Catherine (Nov 25)'] },
        { id: 3, name: 'Basilica of Our Lady of the Mount', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1510', style: 'Indo-Portuguese', patron: 'Our Lady of the Mount', significance: 'One of the earliest churches built in Goa. Offers panoramic views of Old Goa. Important Marian pilgrimage site.', summary: 'One of the oldest churches in Goa perched atop Monte Santo, offering panoramic views and centuries of Marian devotion.', image: 'images/basilica/our-lady-mount.jpg', lat: 15.5067, lng: 73.9125, timings: '8:00 AM – 5:30 PM', festivals: ['Feast of Our Lady (Feb 2)'] },
        { id: 4, name: 'Basilica of the Sacred Heart of Jesus', location: 'Pondicherry', district: 'Puducherry', denomination: 'Roman Catholic', yearBuilt: '1908', style: 'Gothic', patron: 'Sacred Heart of Jesus', significance: 'One of the rare churches in India built in Gothic style with beautiful stained glass panels depicting events from the life of Christ.', summary: 'A stunning Gothic masterpiece in Pondicherry with exquisite stained glass windows depicting the life of Christ.', image: 'images/basilica/sacred-heart-pondy.jpg', lat: 11.9285, lng: 79.8285, timings: '5:30 AM – 8:00 PM', festivals: ['Feast of Sacred Heart (June)'] },
        { id: 5, name: 'San Thome Basilica', location: 'Mylapore, Chennai', district: 'Chennai', denomination: 'Roman Catholic', yearBuilt: '1896', style: 'Neo-Gothic', patron: 'St. Thomas the Apostle', significance: 'Built over the tomb of St. Thomas the Apostle, one of only three churches in the world built over the tomb of an apostle of Jesus.', summary: 'Built over the tomb of St. Thomas the Apostle — one of only three such basilicas in the world, a Neo-Gothic landmark of Chennai.', image: 'images/basilica/san-thome.jpg', lat: 13.0335, lng: 80.2778, timings: '6:00 AM – 8:00 PM', festivals: ['Feast of St. Thomas (July 3)', 'San Thome Festival (Dec)'] },
        { id: 6, name: 'Basilica of Our Lady of Good Health', location: 'Velankanni, Tamil Nadu', district: 'Nagapattinam', denomination: 'Roman Catholic', yearBuilt: '1771', style: 'Indo-Gothic', patron: 'Our Lady of Good Health', significance: 'Known as the "Lourdes of the East". Attracts over 20 million pilgrims annually. Three documented Marian apparitions in the 16th century.', summary: 'The "Lourdes of the East" — India\'s most visited Christian shrine drawing 20 million pilgrims yearly to honour Our Lady of Good Health.', image: 'images/basilica/velankanni.jpg', lat: 10.6824, lng: 79.8490, timings: 'Open 24 hours during festivals', festivals: ['Annual Feast (Aug 29 – Sep 8)', 'Car Festival'] },
        { id: 7, name: 'Basilica of Our Lady of Graces', location: 'Sardhana, Uttar Pradesh', district: 'Meerut', denomination: 'Roman Catholic', yearBuilt: '1822', architect: 'Antonio Reghellini', style: 'Classical European', patron: 'Our Lady of Graces', significance: 'Commissioned by Begum Samru, the Catholic ruler of Sardhana. Unique blend of Mughal patronage and European ecclesiastical architecture.', summary: 'A remarkable classical church commissioned by Begum Samru, blending Mughal patronage with European ecclesiastical grandeur.', image: 'images/basilica/sardhana.jpg', lat: 29.1668, lng: 77.6155, timings: '6:00 AM – 7:00 PM', festivals: ['Feast of Our Lady of Graces (Nov)', 'Begum Samru Anniversary'] },
        { id: 8, name: 'Basilica of the Mount', location: 'Bandra, Mumbai', district: 'Mumbai', denomination: 'Roman Catholic', yearBuilt: '1904', style: 'Neo-Gothic', patron: 'Our Lady of the Mount (Mount Mary)', significance: 'One of the most visited churches in Mumbai. The Bandra Fair held annually is one of the biggest church festivals in India.', summary: 'Mumbai\'s beloved Mount Mary Basilica, home to the famous Bandra Fair and centuries of devotion to Our Lady of the Mount.', image: 'images/basilica/mount-mary.jpg', lat: 19.0431, lng: 72.8195, timings: '6:00 AM – 9:00 PM', festivals: ['Bandra Fair (Sep)', 'Feast of Mount Mary (Sep 8)'] },
        { id: 9, name: 'Basilica of Our Lady of Dolours', location: 'Thrissur, Kerala', district: 'Thrissur', denomination: 'Syro-Malabar Catholic', yearBuilt: '1940', style: 'Indo-Gothic', patron: 'Our Lady of Dolours', significance: 'One of the tallest churches in Asia with a 146-foot belfry. Largest church in India by area. Centre of Syro-Malabar Catholic life.', summary: 'One of Asia\'s tallest churches with its 146-foot belfry, the largest church in India and a Syro-Malabar Catholic landmark.', image: 'images/basilica/thrissur-dolours.jpg', lat: 10.5256, lng: 76.2155, timings: '5:00 AM – 8:00 PM', festivals: ['Feast of Our Lady of Dolours (Nov)', 'Christmas celebrations'] },
        { id: 10, name: 'Basilica of St. Mary', location: 'Bangalore', district: 'Bangalore Urban', denomination: 'Roman Catholic', yearBuilt: '1882', style: 'Gothic', patron: 'St. Mary', significance: 'One of the oldest churches in Bangalore. Known for the annual feast attracting lakhs of devotees from all faiths.', summary: 'Bangalore\'s historic Gothic church known for its grand annual feast that draws hundreds of thousands of devotees of all faiths.', image: 'images/basilica/st-mary-bangalore.jpg', lat: 12.9783, lng: 77.6057, timings: '5:30 AM – 8:30 PM', festivals: ['St. Mary\'s Feast (Sep 1–8)', 'Christmas'] },
        { id: 11, name: 'Cathedral Basilica of St. Joseph', location: 'Allahabad (Prayagraj)', district: 'Prayagraj', denomination: 'Roman Catholic', yearBuilt: '1879', style: 'Italian Renaissance', patron: 'St. Joseph', significance: 'Seat of the Diocese of Allahabad. One of the finest examples of Italian Renaissance architecture in North India.', summary: 'A fine Italian Renaissance cathedral in the heart of Prayagraj, serving as the seat of the Catholic Diocese of Allahabad.', image: 'images/basilica/st-joseph-allahabad.jpg', lat: 25.4380, lng: 81.8464, timings: '6:00 AM – 7:00 PM', festivals: ['Feast of St. Joseph (Mar 19)'] },
        { id: 12, name: 'Basilica of Our Lady of Ransom', location: 'Vallarpadam, Kochi', district: 'Ernakulam', denomination: 'Syro-Malabar Catholic', yearBuilt: '1524', style: 'Modern (rebuilt)', patron: 'Our Lady of Ransom', significance: 'National Shrine of India. Declared by Pope Benedict XVI in 2006. One of the oldest Marian shrines in India.', summary: 'India\'s National Marian Shrine at Vallarpadam, Kochi — one of the oldest Marian devotion centres dating back to 1524.', image: 'images/basilica/vallarpadam.jpg', lat: 9.9847, lng: 76.2688, timings: '5:00 AM – 9:00 PM', festivals: ['Feast of Our Lady of Ransom (Sep 24)', 'Vallarpadam Feast'] },
        { id: 13, name: 'Basilica of St. Thomas', location: 'Chennai', district: 'Chennai', denomination: 'Roman Catholic', yearBuilt: '1523', style: 'Portuguese Colonial', patron: 'St. Thomas', significance: 'Little Mount — believed to be where St. Thomas hid from persecutors. The rock still bears what is believed to be his footprint.', summary: 'The Little Mount shrine where St. Thomas is believed to have sought refuge, bearing his sacred footprint on the rock.', image: 'images/basilica/little-mount.jpg', lat: 13.0116, lng: 80.2277, timings: '6:00 AM – 7:00 PM', festivals: ['Feast of St. Thomas (July 3)'] },
        { id: 14, name: 'Basilica of St. John the Baptist', location: 'Piliyandala, Goa', district: 'South Goa', denomination: 'Roman Catholic', yearBuilt: '1596', style: 'Baroque', patron: 'St. John the Baptist', significance: 'Known for the unique Feast of St. John (São João) where devotثees jump into wells. Beautiful Baroque altar.', summary: 'A beautiful Baroque church famous for the unique São João festival where devotees joyfully leap into wells and ponds.', image: 'images/basilica/st-john-goa.jpg', lat: 15.3807, lng: 73.9772, timings: '7:00 AM – 6:00 PM', festivals: ['São João Festival (June 24)'] },
        { id: 15, name: 'Basilica of the Sacred Heart', location: 'Puducherry', district: 'Puducherry', denomination: 'Roman Catholic', yearBuilt: '1908', style: 'Gothic Revival', patron: 'Sacred Heart of Jesus', significance: 'Rare example of Gothic Revival architecture in South India. 36 stained glass panels imported from France.', summary: 'A magnificent Gothic Revival basilica adorned with 36 stained glass panels from France, a spiritual gem of Puducherry.', image: 'images/basilica/sacred-heart-puducherry.jpg', lat: 11.9340, lng: 79.8312, timings: '5:30 AM – 8:00 PM', festivals: ['Feast of Sacred Heart (June)'] },
        { id: 16, name: 'Basilica of Our Lady of Bandel', location: 'Bandel, West Bengal', district: 'Hooghly', denomination: 'Roman Catholic', yearBuilt: '1599', style: 'Portuguese Colonial', patron: 'Our Lady of Happy Voyage', significance: 'One of the oldest Christian churches in Bengal. The miraculous statue survived Mughal Emperor Shah Jahan\'s destruction attempt.', summary: 'One of Bengal\'s oldest churches (1599) with a miraculous statue that survived Shah Jahan\'s attempts at destruction.', image: 'images/basilica/bandel.jpg', lat: 22.9300, lng: 88.3900, timings: '6:00 AM – 6:00 PM', festivals: ['Bandel Feast (Nov)', 'Christmas'] },
        { id: 17, name: 'Basilica of St. Francis of Assisi', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1661', style: 'Corinthian-Baroque', patron: 'St. Francis of Assisi', significance: 'Contains beautiful gilded woodwork and paintings depicting the life of St. Francis. Now houses the Archaeological Museum of Goa.', summary: 'A Corinthian-Baroque gem in Old Goa with gilded woodwork and paintings, now home to the Archaeological Museum.', image: 'images/basilica/st-francis-goa.jpg', lat: 15.5035, lng: 73.9112, timings: '9:00 AM – 5:00 PM', festivals: ['Feast of St. Francis (Oct 4)'] },
        { id: 18, name: 'Basilica of Mary, Help of Christians', location: 'Shillong, Meghalaya', district: 'East Khasi Hills', denomination: 'Roman Catholic', yearBuilt: '1936', style: 'Gothic', patron: 'Mary Help of Christians', significance: 'Cathedral church of the Archdiocese of Shillong. One of the most prominent churches in Northeast India.', summary: 'The Gothic cathedral of Shillong — the spiritual heart of Catholic faith in Northeast India and seat of the Archdiocese.', image: 'images/basilica/shillong-cathedral.jpg', lat: 25.5684, lng: 91.8830, timings: '6:00 AM – 7:00 PM', festivals: ['Feast of Mary Help of Christians (May 24)'] },
        { id: 19, name: 'Basilica of Our Lady of Lanka', location: 'Ragama, Maharashtra', district: 'Raigad', denomination: 'Roman Catholic', yearBuilt: '1761', style: 'Indo-Portuguese', patron: 'Our Lady of Lanka', significance: 'Major pilgrimage centre for the faithful along the Konkan coast.', summary: 'An important Marian pilgrimage centre along the Konkan coast, drawing devotees with centuries of miraculous traditions.', image: 'images/basilica/our-lady-lanka.jpg', lat: 18.5204, lng: 73.0564, timings: '6:00 AM – 7:00 PM', festivals: ['Annual Feast (Sep)'] },
        { id: 20, name: 'Basilica of the Holy Spirit', location: 'Margao, Goa', district: 'South Goa', denomination: 'Roman Catholic', yearBuilt: '1675', style: 'Baroque', patron: 'Holy Spirit', significance: 'One of the finest examples of late Baroque architecture in Goa. Known for the grand interior and the Feast of the Holy Spirit.', summary: 'A magnificent late Baroque church in Margao, celebrated for its grand interior and the vibrant Feast of the Holy Spirit.', image: 'images/basilica/holy-spirit-margao.jpg', lat: 15.2832, lng: 73.9862, timings: '6:30 AM – 6:30 PM', festivals: ['Feast of Holy Spirit (Pentecost Sunday)'] }
    ],

    // ===== HERITAGE CHURCHES =====
    heritage: [
        { id: 1, name: 'Church of St. Francis of Assisi', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1521', style: 'Manueline-Baroque', significance: 'UNESCO World Heritage Site. Part of the Churches and Convents of Goa. Houses the Archaeological Museum.', summary: 'UNESCO World Heritage church combining Manueline and Baroque styles, part of the historic Churches and Convents of Goa.', image: 'images/heritage/st-francis-oldgoa.jpg', lat: 15.5035, lng: 73.9112, timings: '9:00 AM – 5:00 PM', designation: 'UNESCO World Heritage' },
        { id: 2, name: 'Church of St. Cajetan', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1661', style: 'Corinthian', significance: 'Modeled after St. Peter\'s Basilica in Rome. UNESCO World Heritage Site. Built by Italian friars of the Theatine order.', summary: 'Modeled after St. Peter\'s in Rome, this Corinthian masterpiece was built by Italian Theatine friars and is a UNESCO Heritage Site.', image: 'images/heritage/st-cajetan.jpg', lat: 15.5050, lng: 73.9120, timings: '9:00 AM – 5:30 PM', designation: 'UNESCO World Heritage' },
        { id: 3, name: 'Church of Our Lady of the Rosary', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1544', style: 'Manueline', significance: 'One of the earliest churches in Goa. UNESCO World Heritage. Afonso de Albuquerque watched the battle of Goa from this hilltop.', summary: 'One of Old Goa\'s earliest churches with a storied history — Albuquerque surveyed his conquest from this very hilltop.', image: 'images/heritage/lady-rosary.jpg', lat: 15.5055, lng: 73.9135, timings: '9:30 AM – 5:00 PM', designation: 'UNESCO World Heritage' },
        { id: 4, name: 'St. Augustine Tower', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1602', style: 'Portuguese Late Renaissance', significance: 'The 46-metre tower is all that survives of the once-magnificent Church of St. Augustine. UNESCO World Heritage Site.', summary: 'The towering 46-metre ruin is the sole survivor of the grand Church of St. Augustine, a haunting UNESCO Heritage monument.', image: 'images/heritage/augustine-tower.jpg', lat: 15.5020, lng: 73.9105, timings: '8:30 AM – 5:30 PM', designation: 'UNESCO World Heritage' },
        { id: 5, name: 'Armenian Church of the Holy Nazareth', location: 'Chinsurah, West Bengal', district: 'Hooghly', denomination: 'Armenian Apostolic', yearBuilt: '1695', style: 'Armenian Colonial', significance: 'ASI protected monument. One of the oldest Armenian churches in India. Testament to the Armenian trading community in Bengal.', summary: 'A rare ASI-protected Armenian church from 1695 — a testament to the Armenian trading community that thrived in colonial Bengal.', image: 'images/heritage/armenian-chinsurah.jpg', lat: 22.9000, lng: 88.3900, timings: 'By appointment', designation: 'ASI Protected' },
        { id: 6, name: 'Armenian Church of Holy Nazareth', location: 'Kolkata, West Bengal', district: 'Kolkata', denomination: 'Armenian Apostolic', yearBuilt: '1724', style: 'Armenian Baroque', significance: 'ASI protected. Oldest church in Kolkata. Built by the Armenian community. Contains the oldest working clock in Kolkata.', summary: 'Kolkata\'s oldest church (1724), an Armenian heritage gem containing the city\'s oldest working clock — protected by ASI.', image: 'images/heritage/armenian-kolkata.jpg', lat: 22.5626, lng: 88.3460, timings: '10:00 AM – 4:00 PM', designation: 'ASI Protected' },
        { id: 7, name: 'St. Philomena\'s Cathedral', location: 'Mysore, Karnataka', district: 'Mysore', denomination: 'Roman Catholic', yearBuilt: '1936', style: 'Neo-Gothic', significance: 'One of the tallest churches in Asia. Inspired by Cologne Cathedral. Houses a relic believed to be of St. Philomena.', summary: 'One of Asia\'s tallest churches inspired by Cologne Cathedral, housing sacred relics of St. Philomena in Mysore.', image: 'images/heritage/st-philomena.jpg', lat: 12.3252, lng: 76.6512, timings: '5:00 AM – 6:00 PM', designation: 'State Heritage' },
        { id: 8, name: 'Christ Church', location: 'Shimla, Himachal Pradesh', district: 'Shimla', denomination: 'Church of North India', yearBuilt: '1857', style: 'Neo-Gothic', significance: 'Second oldest church in North India. Iconic landmark of Shimla\'s Ridge. Features five stained glass windows representing faith, hope, charity, fortitude, patience, and humility.', summary: 'Shimla\'s iconic Neo-Gothic landmark on the Ridge — the second oldest church in North India with stunning stained glass windows.', image: 'images/heritage/christ-church-shimla.jpg', lat: 31.1048, lng: 77.1734, timings: '8:00 AM – 6:00 PM', designation: 'State Heritage' },
        { id: 9, name: 'St. Paul\'s Cathedral', location: 'Kolkata, West Bengal', district: 'Kolkata', denomination: 'Church of North India', yearBuilt: '1847', style: 'Indo-Gothic', significance: 'First Anglican cathedral in the eastern world. Designed by Major William Nairn Forbes. Features Florentine Renaissance frescoes.', summary: 'The first Anglican cathedral of the eastern world, graced with Florentine frescoes and Indo-Gothic grandeur in Kolkata.', image: 'images/heritage/st-paul-kolkata.jpg', lat: 22.5448, lng: 88.3426, timings: '9:00 AM – 12:00 PM, 3:00 PM – 6:00 PM', designation: 'State Heritage' },
        { id: 10, name: 'St. Andrew\'s Kirk', location: 'Chennai, Tamil Nadu', district: 'Chennai', denomination: 'Church of South India', yearBuilt: '1821', style: 'Neoclassical', significance: 'Modeled on St. Martin-in-the-Fields, London. Known for its circular seating and magnificent blue dome. ASI protected monument.', summary: 'A magnificent Neoclassical church modeled on London\'s St. Martin-in-the-Fields, famed for its circular seating and blue dome.', image: 'images/heritage/st-andrews-chennai.jpg', lat: 13.0714, lng: 80.2722, timings: '9:00 AM – 5:00 PM', designation: 'ASI Protected' },
        { id: 11, name: 'St. John\'s Church', location: 'Kolkata, West Bengal', district: 'Kolkata', denomination: 'Church of North India', yearBuilt: '1787', style: 'Classical', significance: 'One of the oldest churches in Kolkata. Modeled on St. Martin-in-the-Fields. Tomb of Job Charnock (founder of Calcutta) in the cemetery.', summary: 'One of Kolkata\'s oldest churches housing the tomb of Job Charnock, modeled on London\'s St. Martin-in-the-Fields.', image: 'images/heritage/st-john-kolkata.jpg', lat: 22.5560, lng: 88.3481, timings: '8:00 AM – 5:00 PM', designation: 'ASI Protected' },
        { id: 12, name: 'Church of St. Francis', location: 'Fort Kochi, Kerala', district: 'Ernakulam', denomination: 'Church of South India', yearBuilt: '1503', style: 'Portuguese Colonial', significance: 'Oldest European church in India. Originally Portuguese Catholic, then Dutch Reformed, now CSI. Vasco da Gama was first buried here in 1524.', summary: 'India\'s oldest European church (1503) where Vasco da Gama was first buried — a Portuguese gem now under the CSI.', image: 'images/heritage/st-francis-kochi.jpg', lat: 9.9638, lng: 76.2430, timings: '8:30 AM – 5:00 PM', designation: 'ASI Protected' },
        { id: 13, name: 'All Saints\' Cathedral', location: 'Allahabad (Prayagraj)', district: 'Prayagraj', denomination: 'Church of North India', yearBuilt: '1887', style: 'Gothic Revival', significance: 'Designed by Sir William Emerson (architect of Victoria Memorial). One of the finest examples of Gothic Revival in India. ASI protected.', summary: 'Designed by the architect of the Victoria Memorial, this Gothic Revival masterpiece is one of North India\'s finest churches.', image: 'images/heritage/all-saints-allahabad.jpg', lat: 25.4358, lng: 81.8463, timings: '8:00 AM – 5:00 PM', designation: 'ASI Protected' },
        { id: 14, name: 'Church of the Sacred Heart', location: 'Pondicherry', district: 'Puducherry', denomination: 'Roman Catholic', yearBuilt: '1908', style: 'Gothic', significance: 'Built by French missionaries. The stained glass windows imported from France depict scenes from the life of Christ.', summary: 'French Gothic architecture in Pondicherry with imported stained glass depicting the life of Christ in vivid colour.', image: 'images/heritage/sacred-heart-pondy.jpg', lat: 11.9285, lng: 79.8285, timings: '5:30 AM – 8:00 PM', designation: 'State Heritage' },
        { id: 15, name: 'Santa Cruz Cathedral Basilica', location: 'Fort Kochi, Kerala', district: 'Ernakulam', denomination: 'Roman Catholic', yearBuilt: '1902', style: 'Gothic', significance: 'Originally built in 1505 by the Portuguese. The current structure is the third rebuilding. Elevated to a Cathedral by Pope Paul IV.', summary: 'A Gothic cathedral first erected by the Portuguese in 1505, rebuilt twice, and elevated to Basilica status — Fort Kochi\'s crown jewel.', image: 'images/heritage/santa-cruz-kochi.jpg', lat: 9.9639, lng: 76.2416, timings: '6:00 AM – 6:30 PM', designation: 'Heritage Grade I' }
    ],

    // ===== CHURCHES OF GOA =====
    goa: [
        { id: 1, name: 'Church of Our Lady of the Immaculate Conception', location: 'Panaji, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1619', style: 'Portuguese Baroque', summary: 'The iconic whitewashed church atop zigzagging laterite steps in the heart of Panaji — Goa\'s most photographed church.', image: 'images/goa/immaculate-conception.jpg', lat: 15.4989, lng: 73.8283, timings: '9:00 AM – 12:30 PM, 3:30 PM – 5:30 PM' },
        { id: 2, name: 'Church of St. Alex', location: 'Curtorim, Goa', district: 'South Goa', denomination: 'Roman Catholic', yearBuilt: '1597', style: 'Baroque', summary: 'A hidden Baroque treasure in Curtorim village, known for its seven altars and richly gilded reredos.', image: 'images/goa/st-alex.jpg', lat: 15.2720, lng: 73.9535, timings: '7:00 AM – 6:00 PM' },
        { id: 3, name: 'Church of Our Lady of Miracles', location: 'Mapusa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1594', style: 'Indo-Portuguese', summary: 'Famous for the Milagres feast celebrated by Hindus and Christians alike — a symbol of Goa\'s communal harmony.', image: 'images/goa/lady-miracles.jpg', lat: 15.5910, lng: 73.8078, timings: '7:30 AM – 6:00 PM' },
        { id: 4, name: 'Church of Mae de Deus', location: 'Saligao, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1873', style: 'Neo-Gothic', summary: 'A striking Neo-Gothic church on a hilltop in Saligao, often called one of the most beautiful churches in Goa.', image: 'images/goa/mae-de-deus.jpg', lat: 15.5553, lng: 73.7882, timings: '7:00 AM – 6:30 PM' },
        { id: 5, name: 'Church of St. Cajetan', location: 'Old Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1661', style: 'Corinthian', summary: 'Built by Italian friars modeled after St. Peter\'s Basilica in Rome, a Corinthian architectural marvel in Old Goa.', image: 'images/goa/st-cajetan.jpg', lat: 15.5050, lng: 73.9120, timings: '9:00 AM – 5:30 PM' },
        { id: 6, name: 'Church of St. Anne', location: 'Talaulim, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1695', style: 'Indo-Portuguese Baroque', summary: 'An architectural gem nestled in Talaulim village, showcasing the finest Indo-Portuguese Baroque craftsmanship.', image: 'images/goa/st-anne.jpg', lat: 15.4531, lng: 73.9532, timings: '8:00 AM – 5:30 PM' },
        { id: 7, name: 'Church of Our Lady of Hope', location: 'Candolim, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1563', style: 'Portuguese Colonial', summary: 'One of Goa\'s oldest parish churches in Candolim, steeped in the early history of Portuguese evangelisation.', image: 'images/goa/lady-hope.jpg', lat: 15.5145, lng: 73.7704, timings: '7:00 AM – 6:00 PM' },
        { id: 8, name: 'Chapel of St. Catherine', location: 'Old Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1510', style: 'Portuguese', summary: 'The very first church built in Goa by Afonso de Albuquerque to mark his conquest — where Christianity in Goa began.', image: 'images/goa/st-catherine.jpg', lat: 15.5038, lng: 73.9101, timings: '9:00 AM – 5:00 PM' },
        { id: 9, name: 'Church of the Divine Providence', location: 'Old Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1661', style: 'Baroque', summary: 'Attached to the Convent of the Theatines, a splendid Baroque church distinguished by its dome modeled on Roman design.', image: 'images/goa/divine-providence.jpg', lat: 15.5050, lng: 73.9118, timings: '9:00 AM – 5:00 PM' },
        { id: 10, name: 'Church of Our Lady of Penha de Franca', location: 'Penha de Franca, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1626', style: 'Portuguese', summary: 'Set on a hillock overlooking the Mandovi River, this church offers stunning views and a tranquil spiritual retreat.', image: 'images/goa/penha-de-franca.jpg', lat: 15.4912, lng: 73.8138, timings: '7:30 AM – 5:30 PM' },
        { id: 11, name: 'Church of St. Diogo', location: 'Old Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1640', style: 'Portuguese Baroque', summary: 'Part of the Royal Hospital complex, a quiet Baroque church reflecting Old Goa\'s role as a Portuguese colonial capital.', image: 'images/goa/st-diogo.jpg', lat: 15.5030, lng: 73.9108, timings: '9:00 AM – 5:00 PM' },
        { id: 12, name: 'Church of Our Lady of the Rock', location: 'Rachol, Goa', district: 'South Goa', denomination: 'Roman Catholic', yearBuilt: '1609', style: 'Baroque', summary: 'Attached to the famous Rachol Seminary, one of the earliest educational institutions in Asia, with a magnificent Baroque altar.', image: 'images/goa/lady-rock-rachol.jpg', lat: 15.3186, lng: 73.9576, timings: '8:00 AM – 5:00 PM' },
        { id: 13, name: 'Church of the Three Kings', location: 'Cansaulim, Goa', district: 'South Goa', denomination: 'Roman Catholic', yearBuilt: '1633', style: 'Portuguese', summary: 'Famous for the Three Kings Feast on January 6, where three boys dress as kings and ride up the hill to the hilltop church.', image: 'images/goa/three-kings.jpg', lat: 15.3363, lng: 73.8867, timings: '8:00 AM – 5:30 PM' },
        { id: 14, name: 'Church of St. Thomas', location: 'Aldona, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1596', style: 'Indo-Portuguese', summary: 'Set in the picturesque village of Aldona on the Mapusa River, known for its serene setting and historical significance.', image: 'images/goa/st-thomas-aldona.jpg', lat: 15.5951, lng: 73.8669, timings: '7:00 AM – 6:00 PM' },
        { id: 15, name: 'Church of St. Andrew', location: 'Vasco da Gama, Goa', district: 'South Goa', denomination: 'Roman Catholic', yearBuilt: '1572', style: 'Portuguese Colonial', summary: 'One of the earliest churches in Goa\'s Mormugao taluka, a vital spiritual centre for the port town of Vasco.', image: 'images/goa/st-andrew-vasco.jpg', lat: 15.3953, lng: 73.8150, timings: '7:00 AM – 6:30 PM' },
        { id: 16, name: 'Church of Our Lady of Bethlehem', location: 'Chandor, Goa', district: 'South Goa', denomination: 'Roman Catholic', yearBuilt: '1645', style: 'Portuguese Baroque', summary: 'Standing in historic Chandor, the ancient capital of the Kadamba dynasty, blending Portuguese faith with India\'s deep past.', image: 'images/goa/lady-bethlehem.jpg', lat: 15.3061, lng: 73.9831, timings: '8:00 AM – 5:30 PM' },
        { id: 17, name: 'Church of St. Xavier', location: 'Mapusa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1613', style: 'Portuguese', summary: 'A prominent parish church in the bustling market town of Mapusa, dedicated to Goa\'s patron saint Francis Xavier.', image: 'images/goa/st-xavier-mapusa.jpg', lat: 15.5920, lng: 73.8085, timings: '7:00 AM – 6:00 PM' },
        { id: 18, name: 'Church of St. Estevam', location: 'Jua Island, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1759', style: 'Baroque', summary: 'A Baroque beauty on Jua Island reached by ferry, known for the unique "floating" procession during its annual feast.', image: 'images/goa/st-estevam.jpg', lat: 15.5144, lng: 73.8910, timings: '7:30 AM – 5:30 PM' }
    ],

    // ===== CHURCHES OF KERALA =====
    kerala: [
        { id: 1, name: 'St. Thomas Syro-Malabar Church', location: 'Palayur, Thrissur', district: 'Thrissur', denomination: 'Syro-Malabar Catholic', yearBuilt: '52 AD', style: 'Traditional Kerala', summary: 'One of the seven churches founded by St. Thomas the Apostle in 52 AD — among the oldest Christian congregations on Earth.', image: 'images/kerala/palayur.jpg', lat: 10.4340, lng: 76.0820, timings: '6:00 AM – 7:00 PM' },
        { id: 2, name: 'St. Mary\'s Orthodox Cathedral', location: 'Niranam, Pathanamthitta', district: 'Pathanamthitta', denomination: 'Malankara Orthodox', yearBuilt: '52 AD', style: 'Kerala Traditional', summary: 'Another of St. Thomas\'s seven original churches — an unbroken 2000-year-old Orthodox Christian tradition in the heart of Kerala.', image: 'images/kerala/niranam.jpg', lat: 9.3520, lng: 76.4150, timings: '6:00 AM – 6:30 PM' },
        { id: 3, name: 'St. Mary\'s Forane Church', location: 'Kuravilangad, Kottayam', district: 'Kottayam', denomination: 'Syro-Malabar Catholic', yearBuilt: '105 AD', style: 'Kerala Traditional', summary: 'One of the ancient "Ezharappallikal" (Seven and a Half Churches) with a 1900-year history of unbroken Christian worship.', image: 'images/kerala/kuravilangad.jpg', lat: 9.6225, lng: 76.5250, timings: '5:30 AM – 7:00 PM' },
        { id: 4, name: 'Cheriya Palli (Small Church)', location: 'Kottayam', district: 'Kottayam', denomination: 'Malankara Orthodox', yearBuilt: '1579', style: 'Kerala Colonial', summary: 'Famous for its ancient Persian crosses, Pahlavi inscriptions, and wall paintings — a living museum of Indian Christian heritage.', image: 'images/kerala/cheriya-palli.jpg', lat: 9.5916, lng: 76.5222, timings: '8:00 AM – 5:00 PM' },
        { id: 5, name: 'Valiapalli (Big Church)', location: 'Kottayam', district: 'Kottayam', denomination: 'Malankara Orthodox', yearBuilt: '1550', style: 'Kerala Traditional', summary: 'The historic Valiapalli with its ancient stone cross inscribed in Pahlavi — a cornerstone of Orthodox Christian life in Kottayam.', image: 'images/kerala/valiapalli.jpg', lat: 9.5913, lng: 76.5225, timings: '8:00 AM – 5:30 PM' },
        { id: 6, name: 'St. George Orthodox Church', location: 'Cherpunkal, Kottayam', district: 'Kottayam', denomination: 'Malankara Orthodox', yearBuilt: '335 AD', style: 'Kerala Orthodox', summary: 'One of the oldest churches in India, reputedly founded in 335 AD, with a miraculous icon of St. George drawing thousands.', image: 'images/kerala/cherpunkal.jpg', lat: 9.5780, lng: 76.5670, timings: '5:30 AM – 7:00 PM' },
        { id: 7, name: 'Arthunkal Church', location: 'Arthunkal, Alappuzha', district: 'Alappuzha', denomination: 'Roman Catholic', yearBuilt: '1581', style: 'Portuguese Colonial', summary: 'The famed "Arthunkal Veluthacha" church on the coast, known for the annual penitential feast where devotees crawl on their knees.', image: 'images/kerala/arthunkal.jpg', lat: 9.5710, lng: 76.2960, timings: '5:00 AM – 8:00 PM' },
        { id: 8, name: 'Malayattoor Church', location: 'Malayattoor, Ernakulam', district: 'Ernakulam', denomination: 'Syro-Malabar Catholic', yearBuilt: '1st century', style: 'Modern (rebuilt)', summary: 'The hilltop church where St. Thomas prayed — pilgrims climb the sacred hill carrying crosses, especially during the April feast.', image: 'images/kerala/malayattoor.jpg', lat: 10.1710, lng: 76.5500, timings: '5:00 AM – 7:00 PM' },
        { id: 9, name: 'St. Mary\'s Church', location: 'Manarcad, Kottayam', district: 'Kottayam', denomination: 'Malankara Orthodox', yearBuilt: '800 AD', style: 'Kerala Orthodox', summary: 'Ancient church famous for the 8-day Manarcad Feast (Ettunombu Perunnal) — one of the largest Orthodox Christian festivals in India.', image: 'images/kerala/manarcad.jpg', lat: 9.5530, lng: 76.5610, timings: '5:30 AM – 7:00 PM' },
        { id: 10, name: 'CSI Christ Church', location: 'Trivandrum', district: 'Thiruvananthapuram', denomination: 'Church of South India', yearBuilt: '1838', style: 'Colonial', summary: 'One of the oldest Protestant churches in Trivandrum, a colonial-era spiritual landmark in the heart of the capital.', image: 'images/kerala/csi-trivandrum.jpg', lat: 8.5088, lng: 76.9557, timings: '8:00 AM – 5:00 PM' },
        { id: 11, name: 'Champakulam Church', location: 'Champakulam, Alappuzha', district: 'Alappuzha', denomination: 'Syro-Malabar Catholic', yearBuilt: '427 AD', style: 'Kerala Traditional', summary: 'Believed to be where St. Thomas first landed in Kerala — one of the seven original Apostolic churches of the Malabar Coast.', image: 'images/kerala/champakulam.jpg', lat: 9.4340, lng: 76.3970, timings: '6:00 AM – 6:30 PM' },
        { id: 12, name: 'Kadamattom Church', location: 'Kadamattom, Ernakulam', district: 'Ernakulam', denomination: 'Malankara Orthodox', yearBuilt: '1869', style: 'Gothic', summary: 'Home to the famous "Kadamattom Kathanar" legend — the priest-sorcerer of Kerala folklore who is buried within the church grounds.', image: 'images/kerala/kadamattom.jpg', lat: 9.8920, lng: 76.5490, timings: '7:00 AM – 6:00 PM' },
        { id: 13, name: 'Edappally Church', location: 'Edappally, Kochi', district: 'Ernakulam', denomination: 'Syro-Malabar Catholic', yearBuilt: '594 AD', style: 'Kerala Traditional', summary: 'One of the ancient "Palli" churches of Kerala, serving the Edappally community for over 1400 years.', image: 'images/kerala/edappally.jpg', lat: 10.0261, lng: 76.3125, timings: '5:30 AM – 7:00 PM' },
        { id: 14, name: 'CMS Church', location: 'Kottayam', district: 'Kottayam', denomination: 'Church of South India', yearBuilt: '1816', style: 'Colonial', summary: 'Founded by the Church Missionary Society, this historic church played a pivotal role in the Protestant movement in Kerala.', image: 'images/kerala/cms-kottayam.jpg', lat: 9.5915, lng: 76.5220, timings: '8:00 AM – 5:00 PM' },
        { id: 15, name: 'Parumala Seminary Church', location: 'Parumala, Pathanamthitta', district: 'Pathanamthitta', denomination: 'Malankara Orthodox', yearBuilt: '1876', style: 'Kerala Traditional', summary: 'The tomb-church of St. Gregorios of Parumala — the first canonized Orthodox saint of India and a major pilgrimage centre.', image: 'images/kerala/parumala.jpg', lat: 9.3220, lng: 76.5410, timings: '5:00 AM – 8:00 PM' },
        { id: 16, name: 'Cheriapally (Old Seminary Church)', location: 'Kottayam', district: 'Kottayam', denomination: 'Malankara Orthodox', yearBuilt: '1815', style: 'Colonial', summary: 'Adjacent to the Old Seminary, this historic church stands witness to the earliest theological education in Indian Christianity.', image: 'images/kerala/old-seminary.jpg', lat: 9.5918, lng: 76.5215, timings: '8:00 AM – 5:00 PM' },
        { id: 17, name: 'St. Sebastian\'s Church', location: 'Arthunkal, Alappuzha', district: 'Alappuzha', denomination: 'Roman Catholic', yearBuilt: '1647', style: 'Portuguese Colonial', summary: 'Famous for the "Arthunkal Feast" and the miraculous statue of St. Sebastian brought from Portugal.', image: 'images/kerala/st-sebastian.jpg', lat: 9.5720, lng: 76.2958, timings: '5:30 AM – 7:00 PM' },
        { id: 18, name: 'Udayamperoor Church', location: 'Udayamperoor, Ernakulam', district: 'Ernakulam', denomination: 'Syro-Malabar Catholic', yearBuilt: '52 AD', style: 'Kerala Traditional', summary: 'Site of the historic Synod of Diamper (1599), one of the most consequential events in the history of Indian Christianity.', image: 'images/kerala/udayamperoor.jpg', lat: 9.9437, lng: 76.3175, timings: '6:00 AM – 6:30 PM' },
        { id: 19, name: 'Marth Mariam Cathedral', location: 'Ernakulam, Kochi', district: 'Ernakulam', denomination: 'Syro-Malabar Catholic', yearBuilt: '1953', style: 'Modern', summary: 'The seat of the Archeparchy of Ernakulam-Angamaly, the premier Syro-Malabar Catholic diocese in India.', image: 'images/kerala/marth-mariam.jpg', lat: 9.9812, lng: 76.2894, timings: '5:00 AM – 8:00 PM' },
        { id: 20, name: 'Kodungallur Church', location: 'Kodungallur, Thrissur', district: 'Thrissur', denomination: 'Syro-Malabar Catholic', yearBuilt: '52 AD', style: 'Kerala Traditional', summary: 'Where St. Thomas first landed in India — the very birthplace of Christianity on the Indian subcontinent in 52 AD.', image: 'images/kerala/kodungallur.jpg', lat: 10.2230, lng: 76.1960, timings: '5:30 AM – 7:00 PM' }
    ],

    // ===== CHURCHES OF TAMIL NADU =====
    tamilnadu: [
        { id: 1, name: 'Our Lady of Lourdes Church', location: 'Trichy', district: 'Tiruchirappalli', denomination: 'Roman Catholic', yearBuilt: '1840', style: 'Gothic Revival', summary: 'A magnificent Gothic Revival basilica in Trichy modeled on the Basilica of Lourdes in France, a major pilgrimage centre.', image: 'images/tamilnadu/lourdes-trichy.jpg', lat: 10.8098, lng: 78.6820, timings: '5:30 AM – 8:00 PM' },
        { id: 2, name: 'Our Lady of Snows Church', location: 'Tuticorin (Thoothukudi)', district: 'Thoothukudi', denomination: 'Roman Catholic', yearBuilt: '1582', style: 'Portuguese Colonial', summary: 'The historic church founded during the Portuguese mission in the Pearl Fishery Coast, where St. Francis Xavier preached.', image: 'images/tamilnadu/snows-tuticorin.jpg', lat: 8.7642, lng: 78.1348, timings: '6:00 AM – 7:30 PM' },
        { id: 3, name: 'Madha Church', location: 'Velankanni, Nagapattinam', district: 'Nagapattinam', denomination: 'Roman Catholic', yearBuilt: '1771', style: 'Indo-Gothic', summary: 'The "Lourdes of the East" attracting 20 million pilgrims annually — India\'s most important Marian pilgrimage destination.', image: 'images/tamilnadu/velankanni.jpg', lat: 10.6824, lng: 79.8490, timings: 'Open 24 hours during feasts' },
        { id: 4, name: 'Santhome Cathedral', location: 'Mylapore, Chennai', district: 'Chennai', denomination: 'Roman Catholic', yearBuilt: '1896', style: 'Neo-Gothic', summary: 'Built over the tomb of St. Thomas the Apostle — one of only three churches in the world built over an apostle\'s tomb.', image: 'images/tamilnadu/santhome.jpg', lat: 13.0335, lng: 80.2778, timings: '6:00 AM – 8:00 PM' },
        { id: 5, name: 'St. George\'s Cathedral', location: 'Chennai', district: 'Chennai', denomination: 'Church of South India', yearBuilt: '1816', style: 'Neoclassical', summary: 'The first Anglican cathedral in South Asia, a Neoclassical landmark designed by Colonel James Caldwell in the heart of Chennai.', image: 'images/tamilnadu/st-george-cathedral.jpg', lat: 13.0631, lng: 80.2689, timings: '8:00 AM – 5:00 PM' },
        { id: 6, name: 'St. Mary\'s Church', location: 'Fort St. George, Chennai', district: 'Chennai', denomination: 'Church of South India', yearBuilt: '1680', style: 'British Colonial', summary: 'The oldest surviving Anglican church in India, built within Fort St. George — where Elihu Yale (of Yale University fame) married.', image: 'images/tamilnadu/st-mary-fort.jpg', lat: 13.0802, lng: 80.2875, timings: '9:00 AM – 5:00 PM' },
        { id: 7, name: 'Church of Our Lady of Angels', location: 'Pondicherry', district: 'Puducherry', denomination: 'Roman Catholic', yearBuilt: '1855', style: 'Greco-Roman', summary: 'A beautiful Greco-Roman church in the French Quarter of Pondicherry, reflecting the city\'s unique Franco-Tamil heritage.', image: 'images/tamilnadu/lady-angels-pondy.jpg', lat: 11.9339, lng: 79.8354, timings: '6:00 AM – 8:00 PM' },
        { id: 8, name: 'Tranquebar Zion Church', location: 'Tharangambadi, Nagapattinam', district: 'Nagapattinam', denomination: 'Church of South India', yearBuilt: '1701', style: 'Danish Colonial', summary: 'The first Protestant church in India, built by Danish missionaries Bartholomäus Ziegenbalg and Heinrich Plütschau.', image: 'images/tamilnadu/zion-tranquebar.jpg', lat: 11.0283, lng: 79.8534, timings: '9:00 AM – 5:00 PM' },
        { id: 9, name: 'New Jerusalem Church', location: 'Tharangambadi', district: 'Nagapattinam', denomination: 'Church of South India', yearBuilt: '1718', style: 'Danish Colonial', summary: 'Built by Ziegenbalg as the second Protestant church, it houses India\'s first printing press for Tamil and the missionary\'s tomb.', image: 'images/tamilnadu/new-jerusalem.jpg', lat: 11.0290, lng: 79.8538, timings: '9:00 AM – 5:00 PM' },
        { id: 10, name: 'Schwartz Church', location: 'Thanjavur', district: 'Thanjavur', denomination: 'Church of South India', yearBuilt: '1779', style: 'Colonial', summary: 'Built by the Maratha King Serfoji II for the beloved Danish missionary Christian Friedrich Schwartz — a rare Hindu-built church.', image: 'images/tamilnadu/schwartz.jpg', lat: 10.7905, lng: 79.1378, timings: '8:00 AM – 5:00 PM' },
        { id: 11, name: 'Christ the King Cathedral', location: 'Thanjavur', district: 'Thanjavur', denomination: 'Roman Catholic', yearBuilt: '1933', style: 'Gothic', summary: 'The Gothic-style seat of the Diocese of Thanjavur, an impressive landmark in the city of the Great Chola temples.', image: 'images/tamilnadu/christ-king-thanjavur.jpg', lat: 10.7870, lng: 79.1380, timings: '6:00 AM – 7:00 PM' },
        { id: 12, name: 'St. Joseph\'s Cathedral', location: 'Palayamkottai, Tirunelveli', district: 'Tirunelveli', denomination: 'Roman Catholic', yearBuilt: '1896', style: 'Gothic', summary: 'A grand Gothic cathedral in the missionary heartland of southern Tamil Nadu, seat of the Diocese of Palayamkottai.', image: 'images/tamilnadu/st-joseph-tirunelveli.jpg', lat: 8.7243, lng: 77.7410, timings: '6:00 AM – 7:00 PM' },
        { id: 13, name: 'Holy Cross Church', location: 'Pondicherry', district: 'Puducherry', denomination: 'Roman Catholic', yearBuilt: '1810', style: 'French Colonial', summary: 'A beautiful French Colonial church in the Tamil Quarter, known for its annual Holy Cross feast and vibrant processions.', image: 'images/tamilnadu/holy-cross-pondy.jpg', lat: 11.9310, lng: 79.8280, timings: '6:00 AM – 7:30 PM' },
        { id: 14, name: 'CSI Wesley Church', location: 'Royapettah, Chennai', district: 'Chennai', denomination: 'Church of South India', yearBuilt: '1906', style: 'Gothic Revival', summary: 'A prominent Methodist-heritage church in central Chennai, named after John Wesley and still vibrant with its musical tradition.', image: 'images/tamilnadu/wesley-church.jpg', lat: 13.0540, lng: 80.2610, timings: '8:00 AM – 5:00 PM' },
        { id: 15, name: 'St. Andrew\'s Church', location: 'Egmore, Chennai', district: 'Chennai', denomination: 'Church of South India', yearBuilt: '1821', style: 'Neoclassical', summary: 'Modeled on London\'s St. Martin-in-the-Fields with a magnificent blue dome and circular seating — an ASI-protected treasure.', image: 'images/tamilnadu/st-andrews.jpg', lat: 13.0714, lng: 80.2722, timings: '9:00 AM – 5:00 PM' }
    ],

    // ===== CHURCHES OF NORTHEAST INDIA =====
    northeast: [
        { id: 1, name: 'Cathedral of Mary Help of Christians', location: 'Shillong, Meghalaya', district: 'East Khasi Hills', denomination: 'Roman Catholic', yearBuilt: '1936', style: 'Gothic', summary: 'The grand Gothic cathedral of Shillong, seat of the Archdiocese and spiritual heart of Catholic Northeast India.', image: 'images/northeast/shillong-cathedral.jpg', lat: 25.5684, lng: 91.8830, timings: '6:00 AM – 7:00 PM' },
        { id: 2, name: 'Kohima Cathedral', location: 'Kohima, Nagaland', district: 'Kohima', denomination: 'Roman Catholic', yearBuilt: '1997', style: 'Modern', summary: 'One of the largest cathedrals in Northeast India, reflecting the deep Christian faith of the Naga people.', image: 'images/northeast/kohima-cathedral.jpg', lat: 25.6751, lng: 94.1086, timings: '6:00 AM – 6:00 PM' },
        { id: 3, name: 'Aizawl Presbyterian Church', location: 'Aizawl, Mizoram', district: 'Aizawl', denomination: 'Presbyterian', yearBuilt: '1894', style: 'Modern', summary: 'The mother church of Mizoram\'s Presbyterian tradition, rooted in the Welsh missionary movement that transformed Mizo society.', image: 'images/northeast/aizawl-presbyterian.jpg', lat: 23.7271, lng: 92.7176, timings: '7:00 AM – 5:00 PM' },
        { id: 4, name: 'Centenary Baptist Church', location: 'Kohima, Nagaland', district: 'Kohima', denomination: 'Baptist', yearBuilt: '1972', style: 'Modern', summary: 'Built to commemorate 100 years of Baptist mission in Nagaland — a powerful symbol of the Naga Baptist movement.', image: 'images/northeast/centenary-baptist.jpg', lat: 25.6740, lng: 94.1100, timings: '8:00 AM – 5:00 PM' },
        { id: 5, name: 'Don Bosco Church', location: 'Shillong, Meghalaya', district: 'East Khasi Hills', denomination: 'Roman Catholic', yearBuilt: '1934', style: 'Colonial', summary: 'Part of the Don Bosco campus that houses the famous Museum of Indigenous Cultures — the largest museum in Northeast India.', image: 'images/northeast/don-bosco.jpg', lat: 25.5690, lng: 91.8810, timings: '8:00 AM – 5:30 PM' },
        { id: 6, name: 'Imphal Baptist Church', location: 'Imphal, Manipur', district: 'Imphal West', denomination: 'Baptist', yearBuilt: '1896', style: 'Colonial', summary: 'One of the earliest Baptist churches in Manipur, witness to the dramatic spread of Christianity among the Meitei people.', image: 'images/northeast/imphal-baptist.jpg', lat: 24.8170, lng: 93.9368, timings: '7:00 AM – 5:00 PM' },
        { id: 7, name: 'Jowai Presbyterian Church', location: 'Jowai, Meghalaya', district: 'West Jaintia Hills', denomination: 'Presbyterian', yearBuilt: '1848', style: 'Colonial', summary: 'The pioneering Welsh Presbyterian mission church among the Jaintia (Pnar) people of Meghalaya.', image: 'images/northeast/jowai-presbyterian.jpg', lat: 25.4518, lng: 92.2032, timings: '8:00 AM – 5:00 PM' },
        { id: 8, name: 'Laitumkhrah Presbyterian Church', location: 'Shillong, Meghalaya', district: 'East Khasi Hills', denomination: 'Presbyterian', yearBuilt: '1843', style: 'Gothic', summary: 'The oldest Presbyterian church in Meghalaya, founded by Welsh missionary Thomas Jones — birthplace of Khasi literacy.', image: 'images/northeast/laitumkhrah.jpg', lat: 25.5720, lng: 91.8920, timings: '7:00 AM – 5:00 PM' },
        { id: 9, name: 'Diphu Baptist Church', location: 'Diphu, Assam', district: 'Karbi Anglong', denomination: 'Baptist', yearBuilt: '1923', style: 'Modern', summary: 'A key Baptist church among the Karbi people of Assam\'s hill districts, rooted in American Baptist missionary work.', image: 'images/northeast/diphu-baptist.jpg', lat: 25.8434, lng: 93.4337, timings: '7:00 AM – 5:00 PM' },
        { id: 10, name: 'Mokokchung Baptist Church', location: 'Mokokchung, Nagaland', district: 'Mokokchung', denomination: 'Baptist', yearBuilt: '1876', style: 'Modern', summary: 'One of the earliest churches among the Ao Naga people, marking the dawn of Christianity in the Ao tribal heartland.', image: 'images/northeast/mokokchung.jpg', lat: 26.3230, lng: 94.5208, timings: '7:00 AM – 5:00 PM' },
        { id: 11, name: 'Dimapur Ao Baptist Church', location: 'Dimapur, Nagaland', district: 'Dimapur', denomination: 'Baptist', yearBuilt: '1898', style: 'Modern', summary: 'A historic Baptist church in Nagaland\'s commercial capital, serving the diverse Christian community of Dimapur.', image: 'images/northeast/dimapur-ao.jpg', lat: 25.9053, lng: 93.7276, timings: '7:00 AM – 5:00 PM' },
        { id: 12, name: 'Tura Presbyterian Church', location: 'Tura, Meghalaya', district: 'West Garo Hills', denomination: 'Presbyterian', yearBuilt: '1867', style: 'Colonial', summary: 'The first church established among the Garo people of western Meghalaya by American Baptist missionaries.', image: 'images/northeast/tura.jpg', lat: 25.5135, lng: 90.2169, timings: '7:00 AM – 5:00 PM' }
    ],

    // ===== PILGRIMAGE CHURCHES =====
    pilgrimage: [
        { id: 1, name: 'Velankanni Shrine', location: 'Velankanni, Tamil Nadu', district: 'Nagapattinam', denomination: 'Roman Catholic', yearBuilt: '1771', summary: 'The "Lourdes of the East" — India\'s most visited Christian pilgrimage site with 20 million annual visitors.', image: 'images/pilgrimage/velankanni.jpg', lat: 10.6824, lng: 79.8490, significance: 'Three Marian apparitions in 16th century. Annual 9-day feast draws millions.' },
        { id: 2, name: 'San Thome Basilica', location: 'Chennai, Tamil Nadu', district: 'Chennai', denomination: 'Roman Catholic', yearBuilt: '1896', summary: 'Built over the tomb of St. Thomas — one of three churches worldwide built over an apostle\'s tomb.', image: 'images/pilgrimage/santhome.jpg', lat: 13.0335, lng: 80.2778, significance: 'Tomb of St. Thomas the Apostle.' },
        { id: 3, name: 'Mount Mary Basilica', location: 'Bandra, Mumbai', district: 'Mumbai', denomination: 'Roman Catholic', yearBuilt: '1904', summary: 'Mumbai\'s most beloved church — the annual Bandra Fair attracts millions from all faiths.', image: 'images/pilgrimage/mount-mary.jpg', lat: 19.0431, lng: 72.8195, significance: 'Miraculous statue of the Virgin Mary. Bandra Fair is one of India\'s largest church festivals.' },
        { id: 4, name: 'Malayattoor Church', location: 'Malayattoor, Kerala', district: 'Ernakulam', denomination: 'Syro-Malabar Catholic', yearBuilt: '1st century', summary: 'The sacred hilltop where St. Thomas prayed — pilgrims climb carrying wooden crosses during the April feast.', image: 'images/pilgrimage/malayattoor.jpg', lat: 10.1710, lng: 76.5500, significance: 'Footprint of St. Thomas on the rock. Major Easter pilgrimage.' },
        { id: 5, name: 'Basilica of Bom Jesus', location: 'Old Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1605', summary: 'Houses the sacred relics of St. Francis Xavier — the Exposition draws millions every decade.', image: 'images/pilgrimage/bom-jesus.jpg', lat: 15.5009, lng: 73.9116, significance: 'Mortal remains of St. Francis Xavier. Decennial Exposition.' },
        { id: 6, name: 'Vallarpadam Basilica', location: 'Kochi, Kerala', district: 'Ernakulam', denomination: 'Syro-Malabar Catholic', yearBuilt: '1524', summary: 'India\'s National Marian Shrine — declared by Pope Benedict XVI, a centre of deep Marian devotion.', image: 'images/pilgrimage/vallarpadam.jpg', lat: 9.9847, lng: 76.2688, significance: 'National Shrine of India. 500-year Marian devotion.' },
        { id: 7, name: 'Parumala Church', location: 'Parumala, Kerala', district: 'Pathanamthitta', denomination: 'Malankara Orthodox', yearBuilt: '1876', summary: 'Tomb of St. Gregorios, the first canonized Indian Orthodox saint, drawing lakhs during the November feast.', image: 'images/pilgrimage/parumala.jpg', lat: 9.3220, lng: 76.5410, significance: 'First Indian Orthodox Saint. Annual feast draws 500,000+.' },
        { id: 8, name: 'Bandel Church', location: 'Bandel, West Bengal', district: 'Hooghly', denomination: 'Roman Catholic', yearBuilt: '1599', summary: 'Bengal\'s oldest church with the miraculous statue of Our Lady that survived Mughal destruction.', image: 'images/pilgrimage/bandel.jpg', lat: 22.9300, lng: 88.3900, significance: 'Miraculous statue survived destruction. Major Bengal pilgrimage.' },
        { id: 9, name: 'Little Mount', location: 'Chennai, Tamil Nadu', district: 'Chennai', denomination: 'Roman Catholic', yearBuilt: '1523', summary: 'The cave where St. Thomas hid from his persecutors — his footprint is imprinted on the rock.', image: 'images/pilgrimage/little-mount.jpg', lat: 13.0116, lng: 80.2277, significance: 'Apostolic martyr site. St. Thomas\'s sacred footprint.' },
        { id: 10, name: 'Sardhana Basilica', location: 'Sardhana, UP', district: 'Meerut', denomination: 'Roman Catholic', yearBuilt: '1822', summary: 'The classical church built by Begum Samru, blending Mughal patronage with European Christian architecture.', image: 'images/pilgrimage/sardhana.jpg', lat: 29.1668, lng: 77.6155, significance: 'Unique Mughal-Christian heritage. Begum Samru\'s legacy.' },
        { id: 11, name: 'Arthunkal Church', location: 'Arthunkal, Kerala', district: 'Alappuzha', denomination: 'Roman Catholic', yearBuilt: '1581', summary: 'Known for the penitential feast where thousands crawl on their knees to the church — a profound act of devotion.', image: 'images/pilgrimage/arthunkal.jpg', lat: 9.5710, lng: 76.2960, significance: 'Penitential pilgrimage. St. Sebastian\'s miraculous statue from Portugal.' },
        { id: 12, name: 'Manarcad Church', location: 'Kottayam, Kerala', district: 'Kottayam', denomination: 'Malankara Orthodox', yearBuilt: '800 AD', summary: 'One of India\'s oldest churches — the 8-day Ettunombu Perunnal is among the largest Orthodox festivals.', image: 'images/pilgrimage/manarcad.jpg', lat: 9.5530, lng: 76.5610, significance: 'Ancient Orthodox shrine. Ettunombu 8-day feast.' }
    ],

    // ===== FEATURED CHURCHES =====
    featured: [
        { id: 1, name: 'Basilica of Bom Jesus', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1605', summary: 'UNESCO World Heritage Site housing the sacred relics of St. Francis Xavier — Goa\'s most iconic church.', image: 'images/featured/bom-jesus.jpg', lat: 15.5009, lng: 73.9116 },
        { id: 2, name: 'San Thome Basilica', location: 'Chennai, Tamil Nadu', district: 'Chennai', denomination: 'Roman Catholic', yearBuilt: '1896', summary: 'Built over the tomb of Apostle St. Thomas — one of only three such basilicas in the entire world.', image: 'images/featured/san-thome.jpg', lat: 13.0335, lng: 80.2778 },
        { id: 3, name: 'Velankanni Basilica', location: 'Nagapattinam, Tamil Nadu', district: 'Nagapattinam', denomination: 'Roman Catholic', yearBuilt: '1771', summary: 'The "Lourdes of the East" — India\'s most visited shrine attracting 20 million pilgrims each year.', image: 'images/featured/velankanni.jpg', lat: 10.6824, lng: 79.8490 },
        { id: 4, name: 'St. Philomena\'s Cathedral', location: 'Mysore, Karnataka', district: 'Mysore', denomination: 'Roman Catholic', yearBuilt: '1936', summary: 'One of Asia\'s tallest churches, inspired by Cologne Cathedral, a Neo-Gothic masterpiece in the Palace City.', image: 'images/featured/st-philomena.jpg', lat: 12.3252, lng: 76.6512 },
        { id: 5, name: 'Se Cathedral', location: 'Old Goa, Goa', district: 'North Goa', denomination: 'Roman Catholic', yearBuilt: '1640', summary: 'Once the largest church in Asia, famed for the Golden Bell — the largest bell in Goa and among the largest in Asia.', image: 'images/featured/se-cathedral.jpg', lat: 15.5039, lng: 73.9119 },
        { id: 6, name: 'Basilica of Our Lady of Dolours', location: 'Thrissur, Kerala', district: 'Thrissur', denomination: 'Syro-Malabar Catholic', yearBuilt: '1940', summary: 'The largest church in India with a 146-foot belfry — a towering Syro-Malabar Catholic landmark.', image: 'images/featured/dolours-thrissur.jpg', lat: 10.5256, lng: 76.2155 },
        { id: 7, name: 'Christ Church', location: 'Shimla, Himachal Pradesh', district: 'Shimla', denomination: 'Church of North India', yearBuilt: '1857', summary: 'The iconic Neo-Gothic church on Shimla\'s Ridge — the second oldest church in North India.', image: 'images/featured/christ-church-shimla.jpg', lat: 31.1048, lng: 77.1734 },
        { id: 8, name: 'Mount Mary Basilica', location: 'Bandra, Mumbai', district: 'Mumbai', denomination: 'Roman Catholic', yearBuilt: '1904', summary: 'Mumbai\'s beloved Basilica of Our Lady of the Mount, home to the famous Bandra Fair festival.', image: 'images/featured/mount-mary.jpg', lat: 19.0431, lng: 72.8195 },
        { id: 9, name: 'Church of St. Francis', location: 'Fort Kochi, Kerala', district: 'Ernakulam', denomination: 'Church of South India', yearBuilt: '1503', summary: 'India\'s oldest European church where Vasco da Gama was first buried in 1524.', image: 'images/featured/st-francis-kochi.jpg', lat: 9.9638, lng: 76.2430 },
        { id: 10, name: 'Cathedral of Mary Help of Christians', location: 'Shillong, Meghalaya', district: 'East Khasi Hills', denomination: 'Roman Catholic', yearBuilt: '1936', summary: 'The spiritual heart of Northeast India\'s Catholic faith — a grand Gothic cathedral in the clouds.', image: 'images/featured/shillong-cathedral.jpg', lat: 25.5684, lng: 91.8830 }
    ]
};

// --- Universal getter ---
window.getSectionData = function(type) {
    return window.extraSections[type] || [];
};

// --- Total church count ---
window.getTotalChurchCount = function() {
    var total = 0;
    for (var key in window.extraSections) {
        total += window.extraSections[key].length;
    }
    return total;
};
