window.extraSections = {
  featured: [
    { id: 'f1', name: 'Brihadeeswarar Temple', location: 'Thanjavur', district: 'Thanjavur', deity: 'Lord Shiva', image: 'images/featured/brihadeeswarar.jpg', summary: 'Great Living Chola Temple and UNESCO site.', timings: 'Morning: 6:00 AM - 12:30 PM | Evening: 4:00 PM - 8:30 PM', lat: 10.7828, lng: 79.1318, sthalaVaralaru: 'Built by Raja Raja Chola I in 1010 CE, the Brihadeeswarar Temple stands as one of the greatest achievements of Chola architecture. The vimana (tower) rises to 216 feet and is topped by an 80-ton single granite capstone. Legend says the stone was moved to the top using a 6-km long ramp. The temple was the first in the world to be built entirely of granite. The Nandi (bull) at the entrance, carved from a single rock, weighs 25 tons. Raja Raja Chola I dedicated this temple to Lord Shiva, naming the deity Rajarajeswarar. It was designated a UNESCO World Heritage Site in 1987 as part of the Great Living Chola Temples.' },
    { id: 'f2', name: 'Meenakshi Amman Temple', location: 'Madurai', district: 'Madurai', deity: 'Meenakshi & Sundareswarar', image: 'https://raw.githubusercontent.com/royalatr1973/rajarajan/main/tamil-temples/images/featured/meenakshi.jpg?v=2', summary: 'Iconic Madurai complex with towering gopurams.', timings: 'Morning: 5:00 AM - 12:30 PM | Evening: 4:00 PM - 9:30 PM', lat: 9.9195, lng: 78.1193, sthalaVaralaru: 'According to legend, the Pandya king Malayadhwaja Pandya and his wife Kanchanamala performed a yajna seeking a son. Instead, a three-year-old girl with three breasts emerged from the holy fire. A divine voice told the king to name her Thadaathagai and raise her as a prince. When she met Lord Shiva on Mount Kailash, her third breast disappeared, fulfilling the prophecy that she would marry the man before whom this happened. Lord Shiva came to Madurai as Sundareswarar and married Meenakshi. The temple complex covers 14 acres with 14 gopurams, the tallest being the southern tower at 170 feet.' },
    { id: 'f3', name: 'Ramanathaswamy Temple', location: 'Rameswaram', district: 'Ramanathapuram', deity: 'Lord Shiva', image: 'images/featured/rameswaram.jpg', summary: 'Pilgrimage center known for long corridors.', timings: 'Morning: 5:00 AM - 1:00 PM | Evening: 3:00 PM - 9:00 PM', lat: 9.2881, lng: 79.3174, sthalaVaralaru: 'Lord Rama, after defeating Ravana in Lanka, wished to atone for the sin of killing a Brahmin. He sent Hanuman to bring a Shiva Lingam from Kailash. When Hanuman was delayed, Sita made a small lingam from sand so that the auspicious time would not pass. Hanuman arrived with the Kailash lingam, and Rama installed both. The temple has the longest corridor of any Hindu temple in India, stretching 1,220 meters. There are 22 sacred wells (theerthams) within the temple, each believed to have curative properties.' }
  ],
  navagraha: [
    { id: 'n1', name: 'Suryanar Kovil', location: 'Suryanar Kovil, Aduthurai', district: 'Mayiladuthurai', deity: 'Surya (Sun)', image: 'images/navagraha/1.jpg', summary: 'Dedicated Surya sthalam in the Navagraha circuit.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:30 PM', lat: 11.0012, lng: 79.4040, sthalaVaralaru: 'This is the only temple in India where all nine planetary deities (Navagrahas) are enshrined, with Surya (Sun God) as the presiding deity. According to legend, Sage Kalava was afflicted by leprosy caused by the combined curse of the Navagrahas. He prayed intensely to Surya, who appeared and cured him. Grateful, the sage established this temple. The Sun God here faces east and is depicted with his two consorts, Usha and Pratyusha, riding a chariot driven by seven horses. The temple was built during the Chola period. Devotees visit to seek relief from the malefic effects of the Sun (Surya dosha) in their horoscope, especially for issues related to authority, health, and vitality.' },
    { id: 'n2', name: 'Thingalur Kailasanathar Temple', location: 'Thingalur', district: 'Thanjavur', deity: 'Chandra (Moon)', image: 'images/navagraha/2.jpg', summary: 'Moon-associated sthalam in the Navagraha route.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:00 PM', lat: 10.9854, lng: 79.4455, sthalaVaralaru: 'Thingalur is the sthalam for Chandra (Moon God). According to Puranic legend, Chandra married the 27 daughters of Daksha (representing the 27 nakshatras) but showed excessive affection towards Rohini, neglecting the others. Angered, Daksha cursed Chandra to lose his brilliance. Chandra came here and worshipped Lord Shiva, who placed him on his head (hence Chandrasekhar) and granted that the moon would wax and wane in a monthly cycle rather than losing his light entirely. The presiding deity is Lord Kailasanathar (Shiva). Devotees visit to mitigate adverse effects of a weak Moon, which governs mind, emotions, and mental peace.' },
    { id: 'n3', name: 'Vaitheeswaran Koil', location: 'Vaitheeswaran Koil', district: 'Mayiladuthurai', deity: 'Angaraka / Sevvai (Mars)', image: 'images/navagraha/3.jpg', summary: 'Mars (Sevvai) sthalam; also famed as divine healer temple.', timings: 'Morning: 6:00 AM - 12:30 PM | Evening: 4:00 PM - 9:00 PM', lat: 11.2340, lng: 79.6640, sthalaVaralaru: 'Vaitheeswaran Koil is the sthalam for Angaraka (Mars/Sevvai). Lord Shiva here is worshipped as Vaitheeswaran (Divine Physician) who cured diseases of the Devas after the churning of the ocean. Mars (Angaraka) was born from Shiva\'s sweat drop that fell on the earth. He was afflicted with leprosy and came here to worship Shiva, who cured him. The temple tank "Siddhamirtham" is believed to have curative properties; devotees bathe in it for healing. The temple is also world-famous for Nadi Jothidam (palm leaf astrology), where one\'s past, present, and future are believed to be written on ancient palm leaves by Sage Agastya.' },
    { id: 'n4', name: 'Swetharanyeswarar Temple', location: 'Thiruvenkadu', district: 'Mayiladuthurai', deity: 'Budhan (Mercury)', image: 'images/navagraha/4.jpg', summary: 'Mercury (Budhan) sthalam with rich sthala puranam.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:30 PM', lat: 11.2507, lng: 79.7417, sthalaVaralaru: 'Thiruvenkadu is the sthalam for Budhan (Mercury). The name means "White Forest" (Swetha Aranyam) as Lord Shiva appeared here in a forest of white-barked trees. Budhan (Mercury), the son of Chandra and Tara, worshipped Shiva here to gain wisdom and eloquence. The presiding deity Swetharanyeswarar (Shiva) is self-manifested. The temple has a separate shrine for Budhan. Worshipping here is believed to improve intelligence, communication skills, business acumen, and academic excellence. Budhan governs education, speech, and analytical abilities in Vedic astrology.' },
    { id: 'n5', name: 'Apatsahayeswarar Temple', location: 'Alangudi', district: 'Thiruvarur', deity: 'Guru / Brihaspati (Jupiter)', image: 'images/navagraha/5.jpg', summary: 'Jupiter (Guru) sthalam in Kumbakonam belt.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:30 PM', lat: 10.6680, lng: 79.4010, sthalaVaralaru: 'Alangudi is the sthalam for Guru/Brihaspati (Jupiter), the preceptor of the Devas. Lord Shiva here is Apatsahayeswarar - the one who helps in times of distress. According to legend, when the Devas were defeated by Asuras, Brihaspati prayed to Shiva here for help. Shiva granted him the power to guide and protect the Devas. Jupiter governs wisdom, fortune, children, spirituality, and higher learning. Devotees visit during Guru peyarchi (Jupiter transit) to seek blessings for prosperity, progeny, and spiritual growth. The temple is in the Kumbakonam-Thiruvarur belt, surrounded by paddy fields.' },
    { id: 'n6', name: 'Agneeswarar Temple', location: 'Kanjanur', district: 'Thanjavur', deity: 'Sukran (Venus)', image: 'images/navagraha/6.jpg', summary: 'Venus (Sukran) sthalam near Suryanar Kovil.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:00 PM', lat: 10.9894, lng: 79.3969, sthalaVaralaru: 'Kanjanur is the sthalam for Sukran (Venus), the preceptor of the Asuras. Lord Agni (Fire God) worshipped Shiva here, hence the deity is called Agneeswarar. Sukran once lost his eye when he was kicked by Lord Vishnu during the Vamana avatar. He came to Kanjanur and worshipped Shiva, who restored his vision. Venus governs love, marriage, luxury, beauty, arts, and material comforts. Worshipping here is believed to bring prosperity, remove obstacles in marriage, and bestow artistic talents. The temple also has shrines for all Navagrahas.' },
    { id: 'n7', name: 'Dharbaranyeswarar Temple', location: 'Thirunallar', district: 'Karaikal (Puducherry)', deity: 'Sani (Saturn)', image: 'images/navagraha/7.jpg', summary: 'Saturn (Sani) sthalam, one of the most visited Navagraha temples.', timings: 'Morning: 6:00 AM - 12:30 PM | Evening: 4:00 PM - 9:00 PM', lat: 10.8433, lng: 79.8131, sthalaVaralaru: 'Thirunallar is the sthalam for Sani (Saturn), the most feared yet most worshipped Navagraha. The famous legend of King Nala illustrates Saturn\'s power: despite being a righteous king, Nala suffered immensely during his Sani Dasha (Saturn period), losing his kingdom, wealth, and even his wife Damayanti. He came to Thirunallar and bathed in the sacred tank called "Nala Theertham." Lord Shiva (Dharbaranyeswarar) relieved him from Saturn\'s affliction. This is the most visited Navagraha temple. Devotees flock here especially during Sani peyarchi (Saturn transit) and on Saturdays. Bathing in Nala Theertham is believed to reduce the severity of Sani Dasha.' },
    { id: 'n8', name: 'Naganathaswamy Temple', location: 'Thirunageswaram', district: 'Thanjavur', deity: 'Rahu', image: 'images/navagraha/8.jpg', summary: 'Rahu sthalam known for milk abhishekam phenomenon.', timings: 'Morning: 6:00 AM - 12:30 PM | Evening: 4:00 PM - 8:30 PM', lat: 10.9428, lng: 79.3146, sthalaVaralaru: 'Thirunageswaram is the sthalam for Rahu, the shadow planet (ascending lunar node). The temple is famous for the miraculous "Rahu Kala Pooja" - during Rahu Kalam (the inauspicious period of Rahu each day), milk offered to the Rahu idol is said to change color, turning blue. This phenomenon draws thousands of devotees. According to legend, the serpent Adisesha worshipped Shiva here, hence the name Naganathaswamy (Lord of Serpents). Rahu dosha can cause unexpected troubles, fear, and confusion. Worshipping here with milk abhishekam is believed to neutralize Rahu\'s malefic effects and bring clarity of mind.' },
    { id: 'n9', name: 'Naganathar Temple', location: 'Keezhaperumpallam', district: 'Mayiladuthurai', deity: 'Ketu', image: 'images/navagraha/9.jpg', summary: 'Ketu sthalam completing the Navagraha nine.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:00 PM', lat: 11.2690, lng: 79.7550, sthalaVaralaru: 'Keezhaperumpallam is the sthalam for Ketu, the shadow planet (descending lunar node). Ketu is the body of the demon Swarbhanu, whose head became Rahu after Lord Vishnu severed it with the Sudarshana Chakra during the distribution of amrit. Ketu came to this sacred place and worshipped Lord Shiva to attain salvation and divine status. The presiding deity is Naganathar (Shiva). Ketu governs moksha (liberation), spiritual inclination, and sudden events. Worshipping here is believed to remove Ketu dosha, which can cause mysterious ailments, spiritual confusion, and unexpected life changes. This temple completes the Navagraha circuit.' }
  ],
  panchabhootha: [
    { id: 'p1', name: 'Ekambareswarar Temple', location: 'Kanchipuram', district: 'Kanchipuram', deity: 'Prithvi Lingam (Earth)', image: 'images/panchabhootha/1.jpg', summary: 'Earth element (Prithvi Lingam) among Pancha Bhootha temples.', timings: 'Morning: 6:00 AM - 12:30 PM | Evening: 4:00 PM - 8:30 PM', lat: 12.8520, lng: 79.7006, sthalaVaralaru: 'Ekambareswarar Temple represents Prithvi (Earth) among the Pancha Bhootha Sthalams. According to legend, Goddess Parvati once playfully covered Lord Shiva\'s eyes, plunging the world into darkness. As penance, she came to Kanchipuram and made a Shiva Lingam out of sand (earth) under a mango tree on the banks of the Vegavathi river. Lord Shiva tested her devotion by sending fire and flood, but Parvati embraced the lingam tightly, leaving her marks on it. The Prithvi Lingam here still bears these marks. The temple covers 25 acres with a towering 11-tier rajagopuram (59 meters). The sacred mango tree is believed to be 3,500 years old, with four branches representing the four Vedas, each yielding differently flavored fruits.' },
    { id: 'p2', name: 'Jambukeswarar Temple', location: 'Thiruvanaikaval, Trichy', district: 'Tiruchirapalli', deity: 'Appu Lingam (Water)', image: 'images/panchabhootha/2.jpg', summary: 'Water element (Appu Lingam) temple near Srirangam.', timings: 'Morning: 5:30 AM - 1:00 PM | Evening: 3:00 PM - 9:00 PM', lat: 10.8535, lng: 78.7066, sthalaVaralaru: 'Jambukeswarar Temple represents Appu (Water) among the Pancha Bhootha Sthalams. The legend tells of a spider (Sri) and an elephant (Yanai) who were both devotees of Shiva. The spider wove webs over the lingam as a canopy to protect it from falling leaves, while the elephant poured water to clean it, destroying the webs. This conflict led to their repeated battles across births. The Shiva Lingam here is always partially submerged in water from an underground spring that has never dried up, representing the water element. The presiding Goddess, Akilandeswari, is one of the most powerful forms of the Goddess. Adi Shankaracharya tamed her fierce energy by installing Sri Chakra earrings on her.' },
    { id: 'p3', name: 'Arunachaleswarar Temple', location: 'Thiruvannamalai', district: 'Thiruvannamalai', deity: 'Agni Lingam (Fire)', image: 'images/panchabhootha/3.jpg', summary: 'Fire element (Agni Lingam), famed for Karthigai Deepam.', timings: 'Morning: 5:30 AM - 12:30 PM | Evening: 3:30 PM - 9:30 PM', lat: 12.2317, lng: 79.0670, sthalaVaralaru: 'Arunachaleswarar Temple represents Agni (Fire) among the Pancha Bhootha Sthalams. When Brahma and Vishnu argued about who was superior, Shiva appeared as an infinite column of fire (Jyotirlinga) and challenged them to find its top or bottom. Brahma flew upward as a swan and Vishnu dug downward as a boar; neither could find the end. Shiva then manifested as Arunachala hill, considered the oldest hill on earth. The annual Karthigai Deepam festival features a massive flame lit on the hilltop, visible for miles. The Girivalam (circumambulation) path around Arunachala hill is 14 km long and is walked by millions. Ramana Maharshi attained enlightenment here and his ashram sits at the base of the hill.' },
    { id: 'p4', name: 'Srikalahasteeswara Temple', location: 'Srikalahasti', district: 'Tirupati (Andhra Pradesh)', deity: 'Vayu Lingam (Air)', image: 'images/panchabhootha/4.jpg', summary: 'Air element (Vayu Lingam), ancient Shaivite shrine.', timings: 'Morning: 6:00 AM - 1:00 PM | Evening: 2:00 PM - 9:00 PM', lat: 13.7497, lng: 79.6981, sthalaVaralaru: 'Srikalahasteeswara Temple represents Vayu (Air) among the Pancha Bhootha Sthalams. The temple gets its name from three devoted animals: Sri (spider), Kala (serpent), and Hasti (elephant), who worshipped Shiva here. The spider wove a web shelter over the lingam, the serpent placed a gem on it, and the elephant bathed it with water. The inner sanctum lamp flickers constantly despite no wind, proving the presence of the air element. This is the only Pancha Bhootha temple outside Tamil Nadu, located on the banks of the Swarnamukhi river. It is also called "Dakshina Kasi" (Kashi of the South). The Rahu-Ketu dosha nivarana pooja here is famous across South India.' },
    { id: 'p5', name: 'Thillai Natarajar Temple', location: 'Chidambaram', district: 'Cuddalore', deity: 'Akasha Lingam (Space/Ether)', image: 'images/panchabhootha/5.jpg', summary: 'Space element (Akasha Lingam) at Chidambaram.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 10:00 PM', lat: 11.3994, lng: 79.6937, sthalaVaralaru: 'Thillai Natarajar Temple represents Akasha (Space/Ether) among the Pancha Bhootha Sthalams. This is the only temple where Shiva is worshipped in his Natarajar (Cosmic Dancer) form as the main deity. The Chidambara Rahasyam (Secret of Chidambaram) is a curtain in the sanctum behind which there is empty space decorated with golden vilva leaves - representing the formless nature of God (Akasha). Lord Shiva performed the Ananda Tandavam (Dance of Bliss) here, defeating the demon Muyalakan (symbolizing ignorance). The temple is managed by Dikshitars, a hereditary community of priests. The Arudra Darshan festival draws hundreds of thousands. The temple architecture encodes many cosmic principles including the golden ratio.' }
  ],
  vinayagar: [],
  murugan: [],
  amman: [
    { id: 'a1', name: 'Meenakshi Amman Temple', location: 'Madurai', district: 'Madurai', deity: 'Meenakshi (Parvati)', image: 'images/amman/1.jpg', summary: 'Iconic twin temple for Meenakshi and Sundareswarar with towering gopurams.', timings: 'Morning: 5:00 AM - 12:30 PM | Evening: 4:00 PM - 9:30 PM', lat: 9.9195, lng: 78.1193, sthalaVaralaru: 'The Pandya king Malayadhwaja Pandya and his wife Kanchanamala performed a yajna seeking a son. Instead, a three-year-old girl with three breasts emerged from the holy fire. A divine voice told the king to name her Thadaathagai and raise her as a prince. When she met Lord Shiva on Mount Kailash, her third breast disappeared, fulfilling the prophecy. Lord Shiva came to Madurai as Sundareswarar and married Meenakshi. The complex covers 14 acres with 14 gopurams, the tallest being the southern tower at 170 feet. The temple has over 33,000 sculptures.' },
    { id: 'a2', name: 'Kamakshi Amman Temple', location: 'Kanchipuram', district: 'Kanchipuram', deity: 'Kamakshi (Tripura Sundari)', image: 'images/amman/2.jpg', summary: 'One of the 3 Shakti Peethas; seat of Adi Shankaracharya\'s Sri Chakra.', timings: 'Morning: 5:30 AM - 12:00 PM | Evening: 4:00 PM - 8:30 PM', lat: 12.8423, lng: 79.7125, sthalaVaralaru: 'Kamakshi Amman Temple is one of the three holiest Shakti Peethas (the others being Madurai Meenakshi and Varanasi Visalakshi). Goddess Kamakshi is worshipped in the form of Tripura Sundari, seated in Padmasana (lotus posture). Adi Shankaracharya installed the Sri Chakra here to pacify the fierce energy of the Goddess. She was initially Ugra (fierce), and Shankaracharya transformed her into Shanta (peaceful) Swaroopini. The temple is one of the 51 Shakti Peethas where parts of Goddess Sati\'s body fell. The annual Brahmotsavam in February-March is a grand 9-day festival.' },
    { id: 'a3', name: 'Mariamman Temple', location: 'Samayapuram, Trichy', district: 'Tiruchirapalli', deity: 'Mariamman', image: 'images/amman/3.jpg', summary: 'Most visited Amman temple in Tamil Nadu; famed for healing powers.', timings: 'Morning: 5:30 AM - 1:00 PM | Evening: 3:00 PM - 9:30 PM', lat: 10.8930, lng: 78.7370, sthalaVaralaru: 'Samayapuram Mariamman Temple is the richest and most visited Amman temple in Tamil Nadu. Mariamman is the Goddess of rain and disease — worshipped for curing smallpox, chicken pox, and other ailments. Legend says Goddess Parvati took the form of Mariamman to destroy the demon Tirisiran. The deity is a self-manifested (Swayambhu) idol. Devotees offer lemon garlands and neem leaves. The temple receives more revenue than most temples in Tamil Nadu. During the Panguni and Aadi month festivals, millions of devotees visit. Neem water (marundhu neer) is distributed as sacred healing water.' },
    { id: 'a4', name: 'Akilandeswari Temple', location: 'Thiruvanaikaval, Trichy', district: 'Tiruchirapalli', deity: 'Akilandeswari (Parvati)', image: 'images/amman/4.jpg', summary: 'Powerful Devi shrine within the Jambukeswarar (Water) temple complex.', timings: 'Morning: 5:30 AM - 1:00 PM | Evening: 3:00 PM - 9:00 PM', lat: 10.8535, lng: 78.7066, sthalaVaralaru: 'Akilandeswari (Goddess of the entire universe) resides within the Jambukeswarar Temple, one of the Pancha Bhootha Sthalams (Water). The Goddess was once so fierce that even the Devas feared her. Adi Shankaracharya tamed her energy by installing Sri Chakra earrings (Thaatagam) on her, transforming her from Ugra (fierce) to Shanta (peaceful). The earrings are believed to have been crafted from the poison that emerged during Samudra Manthan. The temple has five enclosures and is surrounded by water from the Cauvery river.' },
    { id: 'a5', name: 'Kali Amman Temple', location: 'Karur (Karuvarai)', district: 'Karur', deity: 'Kali (Bhadrakali)', image: 'images/amman/5.jpg', summary: 'Ancient Bhadrakali temple on the banks of river Amaravathi.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:00 PM', lat: 10.9575, lng: 78.0729, sthalaVaralaru: 'Karur Bhadrakali Temple is one of the most ancient Kali temples in Tamil Nadu. The deity is Bhadrakali — the benevolent yet fierce form of Goddess Kali. According to legend, Goddess Parvati took the form of Bhadrakali to destroy the demon Daruka. The temple is on the banks of the river Amaravathi. Karur was the ancient capital of the Chera dynasty, and this temple has inscriptions dating back over 1,500 years. The annual Panguni festival features grand car processions.' },
    { id: 'a6', name: 'Angala Parameswari Temple', location: 'Melmalayanur', district: 'Viluppuram', deity: 'Angala Parameswari', image: 'images/amman/6.jpg', summary: 'Famed Shakti temple known for fire-walking and trance rituals.', timings: 'Morning: 6:00 AM - 12:30 PM | Evening: 4:00 PM - 8:30 PM', lat: 12.1420, lng: 79.6490, sthalaVaralaru: 'Melmalayanur Angala Parameswari Temple is one of the most powerful Shakti temples in Tamil Nadu, famous for dramatic fire-walking festivals and devotees entering trance states. The Goddess is a fierce form of Parvati who appeared to destroy evil. Devotees perform kavadi and alaku (hook-swinging) during the annual Panguni festival spanning 18 days. Thousands of devotees walk on burning coals barefoot as an offering. The temple is also associated with Siddha traditions and occult sciences.' },
    { id: 'a7', name: 'Karumariamman Temple', location: 'Thiruverkadu, Chennai', district: 'Chennai', deity: 'Karumariamman', image: 'images/amman/7.jpg', summary: 'Popular Amman temple near Chennai; twin deities Karumari and Peri Amman.', timings: 'Morning: 5:30 AM - 12:30 PM | Evening: 4:00 PM - 9:00 PM', lat: 13.0670, lng: 80.1120, sthalaVaralaru: 'Thiruverkadu Karumariamman Temple houses two powerful forms of the Goddess — Karumariamman (dark-complexioned Mariamman) and Peri Amman. The temple has ancient origins and was revitalized during the Chola period. It is one of the Shakti Peethas of the region. Fridays and Tuesdays are especially crowded. During the Tamil month of Aadi, special poojas and abhishekams draw huge crowds from Chennai. The temple also has a Devi Mahatmyam (Durga Saptashati) recitation tradition.' },
    { id: 'a8', name: 'Punnainallur Mariamman Temple', location: 'Punnainallur, Thanjavur', district: 'Thanjavur', deity: 'Mariamman', image: 'images/amman/8.jpg', summary: 'Major Mariamman temple near Thanjavur; one of the oldest Amman shrines.', timings: 'Morning: 6:00 AM - 1:00 PM | Evening: 3:00 PM - 9:00 PM', lat: 10.7410, lng: 79.1070, sthalaVaralaru: 'Punnainallur Mariamman Temple near Thanjavur is one of the oldest and most revered Mariamman temples. The Goddess is believed to be Swayambhu (self-manifested). According to legend, the idol was discovered under a Punnai tree (Calophyllum) by a Chola king who was guided in a dream. The temple was patronized by the Thanjavur Nayaks and Marathas. During the Chithirai festival, the Goddess is taken in a grand chariot procession. Devotees offer turmeric, neem, and kumkum. The temple is a major center for seeking cures from diseases.' },
    { id: 'a9', name: 'Periyapalayathamman Temple', location: 'Coimbatore', district: 'Coimbatore', deity: 'Periyapalayathamman (Shakti)', image: 'images/amman/9.jpg', summary: 'Presiding Amman of Coimbatore city; ancient Shakti shrine.', timings: 'Morning: 5:30 AM - 12:30 PM | Evening: 4:30 PM - 9:00 PM', lat: 11.0005, lng: 76.9620, sthalaVaralaru: 'Periyapalayathamman Temple is the presiding Amman temple of Coimbatore city. The Goddess is a benevolent form of Shakti who protects the city and its people. The temple has been a center of worship for centuries. During the annual Pongal and Navaratri festivals, elaborate decorations and special poojas are held. The Goddess is adorned with silk sarees and gold jewelry during festival days. The temple is located in the heart of the city and is visited daily by thousands.' },
    { id: 'a10', name: 'Kulothamman Temple (Pazhaiyarai)', location: 'Pazhaiyarai, near Kumbakonam', district: 'Thanjavur', deity: 'Kulothamman (Durga)', image: 'images/amman/10.jpg', summary: 'Ancient Chola capital Amman temple; rare Durga with Chola history.', timings: 'Morning: 6:00 AM - 12:00 PM | Evening: 4:00 PM - 8:00 PM', lat: 10.9180, lng: 79.2440, sthalaVaralaru: 'Pazhaiyarai was the early capital of the Chola empire before it moved to Thanjavur. The Kulothamman Temple is the presiding Amman shrine of this historic town. The Goddess Kulothamman (a form of Durga) was the family deity (Kula Deivam) of the Chola dynasty. The temple has rare Chola-period sculptures and inscriptions. It is believed that the Chola kings sought her blessings before going into battle. The temple is surrounded by rice fields and retains a quiet, ancient atmosphere.' }
  ]
};

window.sectionMeta = {
  dd: { title: '108 Divya Desam Temples', page: 'divyadesam.html' },
  pps: { title: '276 Paadal Petra Sthalams', page: 'paadalpetra.html' },
  featured: { title: 'Featured Temples', page: 'featured.html' },
  navagraha: { title: 'Navagraha Temples', desc: 'The nine planetary temples of Tamil Nadu. Each temple is dedicated to one of the Navagrahas and worshipping them is believed to mitigate planetary afflictions.', page: 'navagraha.html' },
  panchabhootha: { title: 'Pancha Bhootha Temples', desc: 'Five ancient Shiva temples representing the five elements of nature — Earth, Water, Fire, Air, and Space.', page: 'panchabhootha.html' },
  vinayagar: { title: 'Vinayagar Temples', desc: 'Sacred temples of Lord Ganesha (Vinayagar) across Tamil Nadu, the remover of obstacles and the god of beginnings.', page: 'vinayagar.html' },
  murugan: { title: 'Murugan Temples', desc: 'Arupadaiveedu and other revered temples of Lord Murugan (Kartikeya), the beloved deity of Tamil Nadu.', page: 'murugan.html' },
  amman: { title: 'Amman Temples', desc: 'Sacred temples of the Divine Mother — Meenakshi, Kamakshi, Mariamman, and other powerful Shakti shrines across Tamil Nadu.', page: 'amman.html' }
};

window.getSectionData = function(type) {
  if (type === 'dd') return (typeof divyaDesams !== 'undefined' ? divyaDesams : []).map(d => ({
    id: String(d.n), n: d.n, name: d.temple, location: d.location, district: d.district, deity: d.deity,
    summary: d.significance || d.legend || '', image: window.getDivyaDesamPhoto ? window.getDivyaDesamPhoto(d.n) : '', raw: d
  }));

  if (type === 'pps') return (typeof paadalPetraSthalams !== 'undefined' ? paadalPetraSthalams : []).map(t => ({
    id: String(t.n), n: t.n, name: t.temple, location: t.location, district: t.district, deity: t.deity,
    summary: t.significance || t.legend || '', image: window.getPaadalPetraPhoto ? window.getPaadalPetraPhoto(t.n) : '', raw: t
  }));

  return (window.extraSections[type] || []).map((t, idx) => ({
    id: t.id || String(idx + 1), name: t.name, location: t.location || '', district: t.district || '', deity: t.deity || '',
    summary: t.summary || '', image: t.image || '', raw: t
  }));
};
